BoxLayout:
    orientation: "vertical"
    BoxLayout:
        orientation: "horizontal"
        Button:
            text: "Clear"
            size_hint_x: 0.25
            on_press: app.clear_text()
        TextInput:
            id: text_field

    BoxLayout:
        orientation: "horizontal"
        Button:
            text: "Greet"
            size_hint_x: 0.25
            on_press: app.handle_greet()
        Label:
            id: output_label
            text: ""